version: '2'

services:
    marmantenimiento:
        image: 'mariadbtpi'
        build: ./MariaDB/.
        container_name: 'conmdbtpi'
        environment: 
        - 'MYSQL_ROOT_PASSWORD=1234'
        ports:
        - '3300:3306'
        volumes:
        - /mysqlMantenimiento:/var/lib/mysql
    paymantenimiento: 
        image: 'payaratpi'
        build: ./Payarafull/.   
        container_name: 'conpayaratpi'
        depends_on:
        - 'marmantenimiento'
        ports:
        - "8080:8080"
        - "4848:4848"
        entrypoint:
        - "./wait-for-mariadb.sh"
        - "172.18.0.1:3300"
        - "-t"
        - "30"
        - "--"
        - "bin/asadmin"
        - "start-domain"
        - "-v"
