version: '3.5'
services:
    marmantenimiento:
        image: 'mariadbtpi'
        build: ./MariaDB/.
        container_name: 'mariamicro'
        environment: 
        - 'MYSQL_ROOT_PASSWORD=1234'
        ports:
        - '3300:3306'
        volumes:
        - /home/mariadblMantenimientoVol:/var/lib/mysql
        networks: 
            tpi_net:
                ipv4_address: 172.38.0.28
    paymantenimiento: 
        image: 'sergiopa'
        build: ./Payaramicro/.   
        container_name: 'paymicro'
        command: dockerize -wait http://172.38.0.28:3306 -timeout 15s
        depends_on:
        - marmantenimiento
        ports:
        - "8080:8181"
        networks: 
            tpi_net:
                ipv4_address: 172.38.0.29
networks: 
    tpi_net:
        ipam:
            driver: default
            config:
            - subnet: 172.38.0.0/16